# Generated by Django 3.2.8 on 2021-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
