# Generated by Django 3.2.8 on 2021-11-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_messagecontact_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagecontact',
            old_name='visibility',
            new_name='seen',
        ),
    ]
