# Generated by Django 3.2.9 on 2021-11-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='blog.PostConnectToCategory', to='blog.Category'),
        ),
    ]
