# Generated by Django 3.2.9 on 2021-11-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(through='blog.PostConnectToCategory', to='blog.Post'),
        ),
    ]
