# Generated by Django 3.2.9 on 2021-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211118_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(through='blog.PostConnectToTag', to='blog.Post'),
        ),
    ]
