# Generated by Django 3.2.9 on 2021-11-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postconnecttotag',
            options={'verbose_name': 'category', 'verbose_name_plural': 'category'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
