# Generated by Django 3.2.9 on 2021-11-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211118_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postconnecttocategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='postconnecttotag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tag'},
        ),
        migrations.AddField(
            model_name='postcomment',
            name='publiched',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('comment_date', models.DateField()),
                ('content_text', models.TextField(max_length=300)),
                ('parent_pk', models.IntegerField()),
                ('publiched', models.BooleanField(default=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
