# Generated by Django 3.2.9 on 2021-11-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211118_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='parent_pk',
            field=models.IntegerField(null=True),
        ),
    ]
