# Generated by Django 3.2.9 on 2021-11-23 15:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postcomment_parent_pk'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postcomment',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(related_name='PCTC', through='blog.PostConnectToCategory', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='parent_pk',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
