# Generated by Django 3.2.9 on 2021-11-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211123_1924'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postcomment',
            managers=[
            ],
        ),
    ]
