# Generated by Django 3.2.9 on 2021-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_postcomment_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
