# Generated by Django 3.2.9 on 2021-11-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postcomment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
